Repository Liberty52/front-end, pull requests merged in 2023-12, with the labels that each got.

#323 Fix Error about add cart (License & Custom Products)
  src/axios/cart/Cart.js
  src/component/order/OrderOptions.js
  src/constants/api.js
  src/constants/header.js
  src/screen/cart/CartList.js
Labels: 🐞 BugFix

#332 fix:이미지 에디터 저장 안 됨 + 배경 transparent
  src/component/order/editor/Preview.js
Labels: 🐞 BugFix

#327 [FEAT] 주문 조회 사진 이슈 해결
  src/screen/inquiry/Detail.css
  src/screen/inquiry/Detail.js
  src/screen/inquiry/Inquiry.css
  src/screen/inquiry/Inquiry.js
Labels: 🚸 Usability, 🐞 BugFix, 🖌 UI/UX

#334 Chore: License tab -> Sample Img tab
  src/component/order/editor/icons/index.js
  src/component/order/editor/panels/PanelsList.js
  src/component/order/editor/panels/panelItems/Images.js
  src/component/order/editor/panels/panelItems/License.js
  src/component/order/editor/panels/panelItems/index.js
  src/constants/mock-data.js
Labels: 🗂 Architecture

#338 Refactor: License -> SampleImages
  src/axios/order/editor/License.js
  src/axios/order/editor/SampleImages.js
  src/component/order/editor/panels/panelItems/SampleImages.js
  src/component/order/editor/panels/panelItems/index.js
  src/constants/api.js
Labels: 🔨 Refactor

#342 issue#340: 라이센스 이미지 크기
  src/component/order/OrderOptions.js
  src/component/order/previewLicense/PreviewLicense.js
  src/component/order/previewLicense/StyledComponents.js
Labels: 🎨 Html&css

#340 issue#339: 리뷰 제품 별로 보이게 하기
  src/component/order/OrderTab.js
  src/component/order/review/Review.js
  src/screen/order/Order.js
Labels: 🔨 Refactor

#343 [Issue#309] Edit Cart Item Image (Custom & License)
  src/axios/cart/Cart.js
  src/component/common/ImageInput.js
  src/constants/api.js
  src/screen/cart/CartList.js
Labels: ✨ Feature
