Repository Liberty52/front-end, pull requests merged in 2023-10, with the labels that each got.

#206 [BUGFIX] Input Label 연결
  src/component/common/Input.js
Labels: 🚸 Usability, 🐞 BugFix

#208 [FEAT] 옵션 별 재고, 추가 금액
  src/component/common/Radio.css
  src/component/common/Radio.js
  src/screen/order/Order.js
Labels: ✨ Feature, 📬 API, 🎨 Html&css

#218 재고량 0인 옵션 디테일 비활성화
  src/screen/order/Order.js
Labels: 📬 API, 🎨 Html&css

#220 [LIB-216] 라이센스 조회
  src/axios/order/editor/AI.js
  src/axios/order/editor/License.js
  src/axios/order/editor/Translation.js
  src/component/order/editor/icons/License.js
  src/component/order/editor/icons/index.js
  src/component/order/editor/panels/PanelsList.js
  src/component/order/editor/panels/panelItems/AI.js
  src/component/order/editor/panels/panelItems/License.js
  src/component/order/editor/panels/panelItems/index.js
  src/constants/api.js
  src/screen/main/Main.css
Labels: ✨ Feature, 📬 API, 🎨 Html&css

#223 [LIB-222] 가상 계좌 결제 시 로딩
  src/screen/order/payment/ConfirmSection.js
  src/screen/order/payment/Payment.js
Labels: 🥰 Accessibility

#225 [ISSUE-224] 리뷰 UI 수정
  src/component/order/review/ReplyContents.js
  src/component/order/review/Review.css
  src/component/order/review/Review.js
  src/screen/order/review/Review.css
  src/screen/order/review/Review.js
Labels: 🎨 Html&css, 🖌 UI/UX

#234 [LIB-71]옵션을 선택하지 않고 개성 추가 수정
  src/screen/order/Order.js
Labels: 🚸 Usability

#236 [CSS] [주문페이지] 배경이미지 입력창 네모
  src/component/common/Image.css
  src/component/common/Image.js
  src/component/common/ImageInput.css
  src/component/common/ImageInput.js
  src/screen/order/Order.css
  src/screen/order/Order.js
Labels: 🎨 Html&css, 🖌 UI/UX

#238 [ISSUE-237][BUGFIX] Review 안 뜸
  src/component/common/Image.js
Labels: 🐞 BugFix

#240 [LIB-239] 이미지 에디터 Preview 안 나오는 버그
  src/component/order/editor/Preview.js
Labels: 🐞 BugFix

#255 [FEAT] 상품 소개글 조회
  src/component/order/Introduction.css
  src/component/order/Introduction.js
  src/component/order/OrderTab.js
  src/screen/order/Order.js
Labels: ✨ Feature

#260 [chore] refactoring read/add/delete/edit cartList
  src/axios/cart/Cart.js
  src/constants/api.js
  src/constants/path.js
  src/constants/token.js
  src/screen/cart/CartList.js
  src/screen/order/Order.js
Labels: ✨ Feature

#259 주문상세정보 페이지 배송정보 조회 추가
  src/axios/inquiry/Inquiry.js
  src/screen/inquiry/Detail.js
Labels: 🚸 Usability

#258 [ISSUE-257] 리뷰 사진 네모로
  src/component/common/Image.js
  src/component/order/review/Review.js
Labels: 🖌 UI/UX

#265 feat:이미지 에디터 프리뷰에서 유광 효과를 표현한다.
  src/component/order/editor/Preview.js
  src/image/icon/glow.png
Labels: ✨ Feature
