Repository Liberty52/front-end, pull requests merged in 2023-11, with the labels that each got.

#267 [LIB-266] 주문 페이지 배송비 보여주기
  src/axios/cart/Cart.js
  src/component/common/Image.js
  src/component/order/Introduction.js
  src/component/order/review/Review.js
  src/constants/path.js
  src/constants/token.js
  src/screen/cart/CartList.js
  src/screen/inquiry/Detail.js
  src/screen/order/Order.js
Labels: 📬 API, 🎨 Html&css

#271 fix: 상품 소개
  src/screen/order/Order.js
Labels: 🐞 BugFix

#277 feat:이미지 생성. 로그인 + 비동기 로딩
  package-lock.json
  package.json
  src/axios/order/editor/AI.js
  src/component/login/SocialLoginButton.js
  src/component/order/editor/panels/panelItems/AI.js
  src/screen/login/Login.js
Labels: 🚸 Usability, ✨ Feature

#279 [LIB-278] 공지 사항 댓글 CR
  src/axios/inquiry/Inquiry.js
  src/axios/support/Notice.js
  src/component/common/Checkbox.css
  src/component/common/Radio.js
  src/component/common/SquareImage.js
  src/component/order/Introduction.js
  src/component/question/QuestionComponent.js
  src/component/support/FaqCardList.js
  src/component/support/NoticeComment.js
  src/component/support/NoticeDetail.js
  src/component/support/style/Notice.js
  src/component/support/style/Support.js
  src/constants/api.js
  src/screen/cart/CartList.js
  src/screen/order/Choose.css
  src/screen/order/Choose.js
Labels: ✨ Feature, 📬 API, 🎨 Html&css, 🖌 UI/UX

#281 [ISSUE-280] npm 종속성으로 인한 build fail 문제 예방
  .github/workflows/ci.yaml
  multistage.Dockerfile
Labels: 🌏 Deploy, 🛠 Dependency, ✅ Test

#283 [ISSUE-282] 공지 댓글 추가 작업
  src/axios/support/Notice.js
  src/component/support/NoticeComment.js
  src/component/support/NoticeDetail.js
Labels: ✨ Feature, 🤝 Collaboration

#274 [LIB-273] 이미지 에디터 텍스트 추가
  src/component/order/editor/icons/Text.js
  src/component/order/editor/icons/index.js
  src/component/order/editor/panels/PanelsList.js
  src/component/order/editor/panels/panelItems/Text.js
  src/component/order/editor/panels/panelItems/index.js
  src/utils/font.js
Labels: ✨ Feature, 🎨 Html&css

#291 [FEAT] 상품이미지 동기화
  src/image/icon/photo-not-found.svg
  src/screen/order/Choose.js
  src/screen/order/Order.css
  src/screen/order/Order.js
Labels: 🚸 Usability, 🎨 Html&css

#292 [ISSUE-289] [주문 페이지] 필수 옵션 / 선택 옵션 체크
  src/App.js
  src/component/order/OrderOptions.js
  src/component/order/ProductImage.js
  src/constants/mode.js
  src/constants/path.js
  src/screen/order/Order.css
  src/screen/order/Order.js
Labels: 🔨 Refactor, 🐞 BugFix, 🎨 Html&css

#294 [HOTFIX] 주문 페이지 금액 NaN
  src/axios/order/Review.js
  src/component/common/ImageInputGroup.js
  src/component/order/OrderOptions.js
  src/component/order/review/Review.js
  src/component/order/review/ReviewContent.js
  src/component/order/review/ReviewPages.js
  src/constants/api.js
  src/screen/order/Order.js
Labels: 🐞 BugFix

#299 [이미지에디터] 상품 페이지로 돌아가기 오류
  src/component/order/editor/toolbax/items/Canvas.js
Labels: 🐞 BugFix

#305 [ISSUE-302] REFACTOR
  src/App.js
  src/axios/axios.js
  src/axios/cart/Cart.js
  src/axios/inquiry/Inquiry.js
  src/axios/login/Login.js
  src/axios/login/SignUp.js
  src/axios/myInfo/MyInfo.js
  src/axios/order/Payment.js
  src/axios/order/Review.js
  src/component/common/Header.js
  src/component/order/Introduction.js
  src/component/order/editor/Common.js
  src/component/order/editor/panels/panelItems/Customize.js
  src/component/order/editor/panels/panelItems/Images.js
  src/component/order/editor/panels/panelItems/License.js
  src/component/order/review/ReviewModal.js
  src/component/support/FaqCardList.js
  src/component/support/NoticeDetail.js
  src/component/support/NoticeList.js
  src/component/support/style/Faq.js
  src/constants/mode.js
  src/constants/path.js
  src/hooks/useAppContext.js
  src/screen/cart/CartList.js
  src/screen/inquiry/Inquiry.js
  src/screen/login/Login.js
  src/screen/login/changePassword/ChangePassword.js
  src/screen/main/Main.js
  src/screen/myInfo/MyInfo.js
  src/screen/order/Choose.js
  src/screen/order/payment/ConfirmSection.js
  src/screen/order/payment/Payment.js
  src/screen/order/payment/PaymentInfo.js
  src/screen/question/QuestionDetail.js
  src/screen/question/QuestionEditor.js
  src/screen/question/QuestionList.js
  src/screen/redirect/Cookie.js
  src/screen/redirect/Redirect.js
  src/screen/support/Support.js
Labels: 🔨 Refactor

#301 [ISSUE-300] [주문 페이지] 옵션 없는 경우 상품 이미지 css 오류
  src/axios/cart/Cart.js
  src/axios/inquiry/Inquiry.js
  src/component/common/Footer.css
  src/component/common/Header.css
  src/component/order/OrderOptions.js
  src/component/order/editor/panels/panelItems/AI.js
  src/component/order/review/ReviewModal.js
  src/screen/inquiry/Detail.js
  src/screen/inquiry/Inquiry.js
  src/screen/order/Order.css
  src/screen/order/Order.js
Labels: ✨ Feature, 🔨 Refactor, 🐞 BugFix, 🎨 Html&css, 🖌 UI/UX

#312 [CSS] Admin page 미리보기와 css 동일하게 변경
  src/component/order/Introduction.css
  src/component/order/Introduction.js
Labels: 🎨 Html&css

#314 [주문 페이지] 옵션 관련 에러
  src/component/order/OrderOptions.js
  src/screen/order/Choose.css
  src/screen/order/Choose.js
Labels: 🔨 Refactor, 🐞 BugFix, 🖌 UI/UX

#316 [문의 페이지] 댓글 수정,삭제
  src/axios/support/Notice.js
  src/component/support/NoticeComment.js
  src/component/support/style/Notice.js
  src/constants/api.js
  src/screen/order/Choose.js
Labels: ✨ Feature, 📬 API

#310 Issue#309 ~ing
  src/axios/cart/Cart.js
  src/component/order/OrderOptions.js
  src/screen/cart/CartList.js
Labels: ✨ Feature

#286 [LIB-272] 라이센스 상품일 때 결제페이지로 state 넘기기
  src/axios/order/Payment.js
  src/component/order/OrderOptions.js
  src/screen/order/payment/Payment.js
Labels: 🚧 WIP, 🗂 Architecture
